language: ruby
rvm:
- 2.2
- 2.2.4
- 2.3.0
deploy:
  provider: heroku
  api_key:
    secure: DUF8BOKlzEs4GtxrpaFXKpN2r4sWd5M+t9lenMb+4zo+h6xJuFuw4GbVn7UpcMY/5SNTzC2FhA5H01JoDlyMvhROp2kL7n/SVzgj20WPM5KYSozta59Wlh1++kwVywptKTcyBhVpxKbGAJQ/AwPpNeU00L4iFQVopvCJwqS2V7jGk/NiYqjUCXM5ExM82wiymCZpl7BMzgraHU6qcSXvjxW18uc0cLnfIixSr9yKEmVF2XlzxMsihpgoHj+RAP0pW/nCsOuRWlD7R1EsCy4SY4I5BpswApLqSs7pr5iIaTGATX1sNJXHCRauMUePXXPkTioc8h2OrRmotCDqZqVMN/37/XZwDR85u3mJDryS9XoNflQAVPy/vBo7yD6UFMo0poNEQbddqktfwexiCAMOHYrospcIq47uM2PJiMP2qiZU2NQnm7saHeYXO5ElqSy8sv7dalZmF+z2+YCZFQq7PG1n63JUC1yPVrLBsL5th8MX4GZ1eLrYmX5C2cCbe8u3EZbEy1a30oz2d4rbrH26N71kQim7T4yz8/P0ZwVbS7xQNyislH2MXVy1CbmZxkCK7mkH4ghHPwIkCbJZrvKarabwJ9JRlwAr8djKlK9gmXdU7Kf5zrRx6xTOZ8l38huRe4kvoiSbNZfaBOUoHoWeeNfdAarh6AYTq0/F/ZazZSk=
  app: projet_lpa2
  on:
    repo: Sgliere/projet
