# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c64581295110adc4d13b53878ba11e060bac181b433695f94982e67baa67f7cb397bcca2ce6c57c0f6b6fe69ab927a837164ea30ef93ca96361c47e4b83949

test:
  secret_key_base: b5028581a603b0149fc23896bfac0a36039047bfe2bcbc76e2fd5ca9203bbd3447b2a534166817bcc9c7fca33e84aad2acc63ed5b4bcfd688de00d8042268e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
